# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import clouddrive_v1_pb2 as clouddrive__v1__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in clouddrive_v1_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CloudDriveFileSrvStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSystemInfo = channel.unary_unary(
                '/clouddrive.CloudDriveFileSrv/GetSystemInfo',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=clouddrive__v1__pb2.CloudDriveSystemInfo.FromString,
                _registered_method=True)
        self.GetToken = channel.unary_unary(
                '/clouddrive.CloudDriveFileSrv/GetToken',
                request_serializer=clouddrive__v1__pb2.GetTokenRequest.SerializeToString,
                response_deserializer=clouddrive__v1__pb2.JWTToken.FromString,
                _registered_method=True)
        self.GetSubFiles = channel.unary_stream(
                '/clouddrive.CloudDriveFileSrv/GetSubFiles',
                request_serializer=clouddrive__v1__pb2.ListSubFileRequest.SerializeToString,
                response_deserializer=clouddrive__v1__pb2.SubFilesReply.FromString,
                _registered_method=True)
        self.CreateFolder = channel.unary_unary(
                '/clouddrive.CloudDriveFileSrv/CreateFolder',
                request_serializer=clouddrive__v1__pb2.CreateFolderRequest.SerializeToString,
                response_deserializer=clouddrive__v1__pb2.CreateFolderResult.FromString,
                _registered_method=True)
        self.AddOfflineFiles = channel.unary_unary(
                '/clouddrive.CloudDriveFileSrv/AddOfflineFiles',
                request_serializer=clouddrive__v1__pb2.AddOfflineFileRequest.SerializeToString,
                response_deserializer=clouddrive__v1__pb2.FileOperationResult.FromString,
                _registered_method=True)
        self.ListOfflineFilesByPath = channel.unary_unary(
                '/clouddrive.CloudDriveFileSrv/ListOfflineFilesByPath',
                request_serializer=clouddrive__v1__pb2.FileRequest.SerializeToString,
                response_deserializer=clouddrive__v1__pb2.OfflineFileListResult.FromString,
                _registered_method=True)
        self.GetRuntimeInfo = channel.unary_unary(
                '/clouddrive.CloudDriveFileSrv/GetRuntimeInfo',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=clouddrive__v1__pb2.RuntimeInfo.FromString,
                _registered_method=True)


class CloudDriveFileSrvServicer:
    """Missing associated documentation comment in .proto file."""

    def GetSystemInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSubFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateFolder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddOfflineFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListOfflineFilesByPath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRuntimeInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CloudDriveFileSrvServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSystemInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemInfo,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=clouddrive__v1__pb2.CloudDriveSystemInfo.SerializeToString,
            ),
            'GetToken': grpc.unary_unary_rpc_method_handler(
                    servicer.GetToken,
                    request_deserializer=clouddrive__v1__pb2.GetTokenRequest.FromString,
                    response_serializer=clouddrive__v1__pb2.JWTToken.SerializeToString,
            ),
            'GetSubFiles': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSubFiles,
                    request_deserializer=clouddrive__v1__pb2.ListSubFileRequest.FromString,
                    response_serializer=clouddrive__v1__pb2.SubFilesReply.SerializeToString,
            ),
            'CreateFolder': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFolder,
                    request_deserializer=clouddrive__v1__pb2.CreateFolderRequest.FromString,
                    response_serializer=clouddrive__v1__pb2.CreateFolderResult.SerializeToString,
            ),
            'AddOfflineFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.AddOfflineFiles,
                    request_deserializer=clouddrive__v1__pb2.AddOfflineFileRequest.FromString,
                    response_serializer=clouddrive__v1__pb2.FileOperationResult.SerializeToString,
            ),
            'ListOfflineFilesByPath': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOfflineFilesByPath,
                    request_deserializer=clouddrive__v1__pb2.FileRequest.FromString,
                    response_serializer=clouddrive__v1__pb2.OfflineFileListResult.SerializeToString,
            ),
            'GetRuntimeInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRuntimeInfo,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=clouddrive__v1__pb2.RuntimeInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'clouddrive.CloudDriveFileSrv', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('clouddrive.CloudDriveFileSrv', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CloudDriveFileSrv:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSystemInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clouddrive.CloudDriveFileSrv/GetSystemInfo',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            clouddrive__v1__pb2.CloudDriveSystemInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clouddrive.CloudDriveFileSrv/GetToken',
            clouddrive__v1__pb2.GetTokenRequest.SerializeToString,
            clouddrive__v1__pb2.JWTToken.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSubFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/clouddrive.CloudDriveFileSrv/GetSubFiles',
            clouddrive__v1__pb2.ListSubFileRequest.SerializeToString,
            clouddrive__v1__pb2.SubFilesReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateFolder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clouddrive.CloudDriveFileSrv/CreateFolder',
            clouddrive__v1__pb2.CreateFolderRequest.SerializeToString,
            clouddrive__v1__pb2.CreateFolderResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddOfflineFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clouddrive.CloudDriveFileSrv/AddOfflineFiles',
            clouddrive__v1__pb2.AddOfflineFileRequest.SerializeToString,
            clouddrive__v1__pb2.FileOperationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListOfflineFilesByPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clouddrive.CloudDriveFileSrv/ListOfflineFilesByPath',
            clouddrive__v1__pb2.FileRequest.SerializeToString,
            clouddrive__v1__pb2.OfflineFileListResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRuntimeInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clouddrive.CloudDriveFileSrv/GetRuntimeInfo',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            clouddrive__v1__pb2.RuntimeInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
