"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-13 18:30:33.689161
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001_initial'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('btih', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("length(btih) = 40 AND btih = lower(btih) AND btih NOT GLOB '*[^0-9a-f]*'", name=op.f('ck_candidates_normalized_btih')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidates')),
    sa.UniqueConstraint('btih', name=op.f('uq_candidates_btih'))
    )
    op.create_table('content_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('namespace', sa.String(length=100), nullable=False),
    sa.Column('raw_key', sa.String(length=300), nullable=False),
    sa.Column('normalized_key', sa.String(length=300), nullable=False),
    sa.Column('title', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_items')),
    sa.UniqueConstraint('namespace', 'normalized_key', name=op.f('uq_content_items_namespace'))
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('settings_json', sa.JSON(), nullable=False),
    sa.Column('destination_subdir', sa.String(length=500), nullable=False),
    sa.Column('top_n', sa.Integer(), server_default='20', nullable=False),
    sa.Column('daily_time', sa.String(length=8), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles'))
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profiles_archived_at'), ['archived_at'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings'))
    )
    op.create_table('setup_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_setup_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_setup_tokens_token_hash'))
    )
    op.create_table('source_health',
    sa.Column('source_kind', sa.String(length=30), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_latency_ms', sa.Integer(), nullable=True),
    sa.Column('last_result_count', sa.Integer(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error_code', sa.String(length=100), nullable=True),
    sa.Column('last_error_summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('source_kind', 'source_name', name=op.f('pk_source_health'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('session_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_user_id'), ['user_id'], unique=False)

    op.create_table('profile_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('source_kind', sa.String(length=30), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_profile_sources_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_sources')),
    sa.UniqueConstraint('profile_id', 'source_kind', 'source_name', name=op.f('uq_profile_sources_profile_id'))
    )
    with op.batch_alter_table('profile_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_sources_profile_id'), ['profile_id'], unique=False)

    op.create_table('runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('trigger', sa.String(length=30), nullable=False),
    sa.Column('config_snapshot', sa.JSON(), nullable=False),
    sa.Column('stats_json', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_runs_profile_id_profiles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runs'))
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_profile_id'), ['profile_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_sessions_token_hash'))
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('run_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('content_item_id', sa.Integer(), nullable=False),
    sa.Column('result_status', sa.String(length=30), nullable=False),
    sa.Column('rankings_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], name=op.f('fk_run_items_content_item_id_content_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_run_items_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_items')),
    sa.UniqueConstraint('run_id', 'content_item_id', name=op.f('uq_run_items_run_id'))
    )
    with op.batch_alter_table('run_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_items_content_item_id'), ['content_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_items_run_id'), ['run_id'], unique=False)

    op.create_table('run_source_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('source_kind', sa.String(length=30), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_run_source_results_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_source_results')),
    sa.UniqueConstraint('run_id', 'source_kind', 'source_name', name=op.f('uq_run_source_results_run_id'))
    )
    with op.batch_alter_table('run_source_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_source_results_run_id'), ['run_id'], unique=False)

    op.create_table('candidate_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_item_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('magnet_uri', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), server_default='', nullable=False),
    sa.Column('size_mb', sa.Float(), nullable=True),
    sa.Column('seeders', sa.Integer(), nullable=True),
    sa.Column('chinese_subtitles', sa.String(length=10), nullable=False),
    sa.Column('uncensored', sa.String(length=10), nullable=False),
    sa.Column('uhd', sa.String(length=10), nullable=False),
    sa.Column('notes_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_candidate_evidence_candidate_id_candidates'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_item_id'], ['run_items.id'], name=op.f('fk_candidate_evidence_run_item_id_run_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_evidence'))
    )
    with op.batch_alter_table('candidate_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_evidence_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_evidence_run_item_id'), ['run_item_id'], unique=False)

    op.create_table('download_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('download_client_key', sa.String(length=100), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('run_item_id', sa.Integer(), nullable=True),
    sa.Column('content_item_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('idempotency_generation', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('external_reference', sa.Text(), nullable=True),
    sa.Column('manual_completed', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_download_tasks_candidate_id_candidates'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], name=op.f('fk_download_tasks_content_item_id_content_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_download_tasks_profile_id_profiles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_item_id'], ['run_items.id'], name=op.f('fk_download_tasks_run_item_id_run_items'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_download_tasks')),
    sa.UniqueConstraint('download_client_key', 'candidate_id', 'idempotency_generation', name='uq_download_tasks_client_candidate_generation'),
    sa.UniqueConstraint('download_client_key', 'content_item_id', 'idempotency_generation', name='uq_download_tasks_client_content_generation')
    )
    with op.batch_alter_table('download_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_download_tasks_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_download_tasks_content_item_id'), ['content_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_download_tasks_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_download_tasks_run_item_id'), ['run_item_id'], unique=False)
        batch_op.create_index('ix_download_tasks_status_updated', ['status', 'updated_at'], unique=False)

    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_item_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('reasons_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_evaluations_candidate_id_candidates'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_item_id'], ['run_items.id'], name=op.f('fk_evaluations_run_item_id_run_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluations')),
    sa.UniqueConstraint('run_item_id', 'candidate_id', name=op.f('uq_evaluations_run_item_id'))
    )
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluations_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluations_run_item_id'), ['run_item_id'], unique=False)

    op.create_table('download_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('download_task_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['download_task_id'], ['download_tasks.id'], name=op.f('fk_download_events_download_task_id_download_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_download_events')),
    sa.UniqueConstraint('download_task_id', 'sequence', name=op.f('uq_download_events_download_task_id'))
    )
    with op.batch_alter_table('download_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_download_events_download_task_id'), ['download_task_id'], unique=False)

    op.execute(
        "CREATE TRIGGER prevent_run_snapshot_update "
        "BEFORE UPDATE OF config_snapshot ON runs "
        "BEGIN SELECT RAISE(ABORT, 'run config snapshot is immutable'); END"
    )
    op.execute(
        "CREATE TRIGGER prevent_download_event_update "
        "BEFORE UPDATE ON download_events "
        "BEGIN SELECT RAISE(ABORT, 'download events are immutable'); END"
    )
    op.execute(
        "CREATE TRIGGER prevent_download_event_delete "
        "BEFORE DELETE ON download_events "
        "BEGIN SELECT RAISE(ABORT, 'download events are immutable'); END"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS prevent_download_event_delete")
    op.execute("DROP TRIGGER IF EXISTS prevent_download_event_update")
    op.execute("DROP TRIGGER IF EXISTS prevent_run_snapshot_update")
    with op.batch_alter_table('download_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_download_events_download_task_id'))

    op.drop_table('download_events')
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluations_run_item_id'))
        batch_op.drop_index(batch_op.f('ix_evaluations_candidate_id'))

    op.drop_table('evaluations')
    with op.batch_alter_table('download_tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_download_tasks_status_updated')
        batch_op.drop_index(batch_op.f('ix_download_tasks_run_item_id'))
        batch_op.drop_index(batch_op.f('ix_download_tasks_profile_id'))
        batch_op.drop_index(batch_op.f('ix_download_tasks_content_item_id'))
        batch_op.drop_index(batch_op.f('ix_download_tasks_candidate_id'))

    op.drop_table('download_tasks')
    with op.batch_alter_table('candidate_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_evidence_run_item_id'))
        batch_op.drop_index(batch_op.f('ix_candidate_evidence_candidate_id'))

    op.drop_table('candidate_evidence')
    with op.batch_alter_table('run_source_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_source_results_run_id'))

    op.drop_table('run_source_results')
    with op.batch_alter_table('run_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_items_run_id'))
        batch_op.drop_index(batch_op.f('ix_run_items_content_item_id'))

    op.drop_table('run_items')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_profile_id'))

    op.drop_table('runs')
    with op.batch_alter_table('profile_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_sources_profile_id'))

    op.drop_table('profile_sources')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_user_id'))

    op.drop_table('audit_events')
    op.drop_table('users')
    op.drop_table('source_health')
    op.drop_table('setup_tokens')
    op.drop_table('settings')
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profiles_archived_at'))

    op.drop_table('profiles')
    op.drop_table('content_items')
    op.drop_table('candidates')
    # ### end Alembic commands ###
