"""download task tracking

Revision ID: 0002_download_tracking
Revises: 0001_initial
Create Date: 2026-08-13 18:46:20.112250
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002_download_tracking'
down_revision: Union[str, Sequence[str], None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supersedes_task_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('destination_path', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('ownership_acquired', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('baseline_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('completion_state_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('attention_after_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_error_code', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_error_summary', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_download_tasks_supersedes_task_id'), ['supersedes_task_id'], unique=False)
        batch_op.create_index(
            'uq_download_tasks_destination_ownership',
            ['download_client_key', 'destination_path'],
            unique=True,
            sqlite_where=sa.text(
                "destination_path IS NOT NULL AND ownership_acquired = 0 "
                "AND status IN ('submitting', 'submitted', 'downloading', 'attention_required')"
            ),
        )
        batch_op.create_foreign_key(batch_op.f('fk_download_tasks_supersedes_task_id_download_tasks'), 'download_tasks', ['supersedes_task_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_download_tasks_supersedes_task_id_download_tasks'), type_='foreignkey')
        batch_op.drop_index('uq_download_tasks_destination_ownership')
        batch_op.drop_index(batch_op.f('ix_download_tasks_supersedes_task_id'))
        batch_op.drop_column('last_error_summary')
        batch_op.drop_column('last_error_code')
        batch_op.drop_column('attention_after_at')
        batch_op.drop_column('completion_state_json')
        batch_op.drop_column('baseline_json')
        batch_op.drop_column('destination_path')
        batch_op.drop_column('ownership_acquired')
        batch_op.drop_column('supersedes_task_id')

    # ### end Alembic commands ###
